server:
  port: 8000

spring:
  application:
    name: moga-api-gateway
  main:
    web-application-type: reactive
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
    gateway:
      enabled: true
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: user-service
          uri: lb://moga-user-service
          order: 1
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: cart-service
          uri: lb://moga-cart-service
          order: 1
          predicates:
            - Path=/api/cart/**
          filters:
            - StripPrefix=1
        - id: product-service
          uri: lb://moga-product-service
          order: 1
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: lb://moga-order-service
          order: 1
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1
        - id: brand-service
          uri: lb://moga-product-service
          order: 1
          predicates:
            - Path=/api/brand/**
          filters:
            - StripPrefix=1
        - id: category-service
          uri: lb://moga-product-service
          order: 1
          predicates:
            - Path=/api/category/**
          filters:
            - StripPrefix=1
  devtools:
    livereload:
      port: 35734
  rabbitmq:
    username: admin
    password: admin
management:
  endpoints:
    web:
      exposure:
        include: "health"

logging:
  level:
    org.springframework:cloud.gateway: debug