server:
  port: 9000

spring:
  application:
    name: moga-api-gateway
  main:
    web-application-type: reactive
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: user-service
          uri: lb://moga-user-service
          order: 1
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
      enabled: true
  devtools:
    livereload:
      port: 35734
  rabbitmq:
    username: admin
    password: admin
management:
  endpoints:
    web:
      exposure:
        include: "health"

logging:
  level:
    org.springframework:cloud.gateway: debug