server:
  port: 9002

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/moga-mall-product-db?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    druid:
      min-idle: 1
      max-wait: -1
      validation-query: SELECT 1
    username: root
    password: 802324
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 83fc6b20-4f5d-4b91-a645-04d3c32b337a
        username: nacos
        password: nacos
  devtools:
    livereload:
      port: 35730
  mvc:
    pathmatch:
      # 解决knife4报错
      matching-strategy: ant_path_matcher
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        min-idle: 1
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  rabbitmq:
    username: admin
    password: admin
management:
  endpoints:
    web:
      exposure:
        include: "health"
