server:
  port: 8002

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/moga_mall_pms?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    druid:
      min-idle: 1
      max-wait: -1
      validation-query: SELECT 1
    username: root
    password: 802324
  cache:
    type: redis
    redis:
      time-to-live: 3600000
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: 4cea06b9-f119-48d0-8fa4-d79a17d21377
  devtools:
    livereload:
      port: 35730
  mvc:
    pathmatch:
      # 解决knife4报错
      matching-strategy: ant_path_matcher
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        min-idle: 1
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  rabbitmq:
    username: admin
    password: admin
management:
  endpoints:
    web:
      exposure:
        include: "health"
mybatis-plus:
  global-config:
    db-config:
#      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)

# MinIO配置信息
minio:
  endpoint: http://127.0.0.1:9001
  access-key: minio
  secret-key: minio@802324
  bucket-name: moga-mall-product